# Site settings
title:          Ask Karin Changelog
description:    "The latest product updates from Ask Karin."
url:            "https://ask-karin.com/"
theme:          tale

# Author
author:
  name:         Anas Gamrani
  url:          https://freelancer.com/u/Varulv1997

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
# - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
# exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale